[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "biogeme"
dynamic = ["version"]
requires-python = ">=3.12"
description = "Estimation and application of discrete choice models"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Michel Bierlaire", email = "michel.bierlaire@epfl.ch" }
]

classifiers = [
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: C++",
    "Programming Language :: Cython",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython"
]

dependencies = [
    "pandas>=2.3.3, <3",
    "scipy>=1.17.1, <2",
    "tqdm>=4.68.1",
    "tomlkit>=0.15.0",
    "python-levenshtein>=0.27.3",
    "fuzzywuzzy>=0.18.0",
    "biogeme_optimization>=0.0.11, <0.1",
    "matplotlib>=3.10.9, <4",
    "numpy>=2.4.6, <3",
    "ipython>=9.14.1",
    "Jinja2>=3.1.6",
    "PyYAML>=6.0.3",
    "jax >= 0.10.1",
    "tabulate >= 0.10.0",
    "joblib >= 1.5.3",
    "tqdm_joblib >= 0.0.5",
    "pymc >= 6.0.1",
    "numpyro >= 0.21.0",
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
]

[project.optional-dependencies]
testing = [
    "pytest>=9.0.3",
    "pytest-cov >= 4.0.0",
    "tox >= 4.35.0"
]

[project.urls]
Homepage = "https://biogeme.epfl.ch/sphinx/index.html"
Documentation = "https://biogeme.epfl.ch/sphinx/index.html"
Code = "https://github.com/michelbierlaire/biogeme"


[tool.setuptools]
package-dir = { "" = "src" }



[tool.setuptools.dynamic]
version = { attr = "biogeme.version.__version__" }

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools.package-data]
biogeme = ["data/data/*.dat"]

[tool.setuptools.exclude-package-data]
biogeme = ["*/__pycache__", "*/__pycache__/*", "*/*.pyc", "__pycache__", "*.pyc"]

[tool.black]
line-length = 88
skip-string-normalization = true

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E501"]
extend-select = ["UP034"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[dependency-groups]
dev = [
    "black>=26.3.1",
    "pytest>=9.0.2",
    "ruff>=0.15.8",
    "tox>=4.35.0",
    "icecream>=2.2.0",
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx_gallery",
    "sphinx_autodoc_typehints",
    "myst-parser",
    "furo",
    "twine>=6.2.0",
]
