[tox]
envlist = py312, py313, py314
isolated_build = True

[gh-actions]
python:
  3.12: py312
  3.13: py313
  3.14: py314

  


[testenv]
# install pytest in the virtualenv where commands will be executed
allowlist_externals = pytest

deps =
     pytest
     pytest-cov

commands =
    # NOTE: you can run any command line tool here - not just tests
    pytest


[testenv:py314-pandas3]
description = Run the test suite with pandas 3
basepython = python3.14
deps =
     pandas>=3.0.2,<4
     pytest
     pytest-cov
commands =
    pytest
