"""

Triangular mixture of logit
===========================

 Example of a mixture of logit models, using Monte-Carlo integration.
 The mixing distribution is specified by the user. Here, a triangular
 distribution.

:author: Michel Bierlaire, EPFL
:date: Wed Apr 12 18:24:18 2023


"""

import numpy as np
import biogeme.biogeme_logging as blog
import biogeme.biogeme as bio
from biogeme import models
from biogeme.expressions import Beta, bioDraws, log, MonteCarlo
from biogeme.native_draws import RandomNumberGeneratorTuple
from biogeme.parameters import Parameters

# %%
# See the data processing script: :ref:`swissmetro_data`.
from swissmetro_data import (
    database,
    CHOICE,
    CAR_AV_SP,
    TRAIN_AV_SP,
    TRAIN_TT_SCALED,
    TRAIN_COST_SCALED,
    SM_TT_SCALED,
    SM_COST_SCALED,
    CAR_TT_SCALED,
    CAR_CO_SCALED,
    SM_AV,
)

logger = blog.get_screen_logger(level=blog.INFO)
logger.info('Example b25triangular_mixture.py')

# %%
# Parameters to be estimated.
ASC_CAR = Beta('ASC_CAR', 0, None, None, 0)
ASC_TRAIN = Beta('ASC_TRAIN', 0, None, None, 0)
ASC_SM = Beta('ASC_SM', 0, None, None, 1)
B_COST = Beta('B_COST', 0, None, None, 0)

# %%
# Define a random parameter with a triangular distribution, designed
# to be used for Monte-Carlo simulation. The triangular distribution
# is not directly available from Biogeme. The draws have to be
# generated by a function provided by the user.

# %%
# Mean of the distribution.
B_TIME = Beta('B_TIME', 0, None, None, 0)

# %%
# Scale of the distribution.
# It is advised not to use 0 as starting value for the following parameter.
B_TIME_S = Beta('B_TIME_S', 1, None, None, 0)


# %%
# Function generating the draws.
def the_triangular_generator(sample_size: int, number_of_draws: int) -> np.ndarray:
    """
    User-defined random number generator to the database.
    See the numpy.random documentation to obtain a list of other distributions.
    """
    return np.random.triangular(-1, 0, 1, (sample_size, number_of_draws))


# %%
# Associate the function with a name.
myRandomNumberGenerators = {
    'TRIANGULAR': RandomNumberGeneratorTuple(
        generator=the_triangular_generator,
        description='Draws from a triangular distribution',
    )
}

# %%
# Submit the generator to the database.
database.set_random_number_generators(myRandomNumberGenerators)

# %%
# Define a random parameter with a triangular distribution, designed to be used
# for Monte-Carlo simulation.
B_TIME_RND = B_TIME + B_TIME_S * bioDraws('b_time_rnd', 'TRIANGULAR')

# %%
# Definition of the utility functions.
V1 = ASC_TRAIN + B_TIME_RND * TRAIN_TT_SCALED + B_COST * TRAIN_COST_SCALED
V2 = ASC_SM + B_TIME_RND * SM_TT_SCALED + B_COST * SM_COST_SCALED
V3 = ASC_CAR + B_TIME_RND * CAR_TT_SCALED + B_COST * CAR_CO_SCALED

# %%
# Associate utility functions with the numbering of alternatives
V = {1: V1, 2: V2, 3: V3}

# %%
# Associate the availability conditions with the alternatives
av = {1: TRAIN_AV_SP, 2: SM_AV, 3: CAR_AV_SP}

# %%
# Conditional to b_time_rnd, we have a logit model (called the kernel)
prob = models.logit(V, av, CHOICE)

# %%
# We integrate over b_time_rnd using Monte-Carlo
logprob = log(MonteCarlo(prob))

# %%
# As the objective is to illustrate the
# syntax, we calculate the Monte-Carlo approximation with a small
# number of draws.
parameters = Parameters()
parameters.set_value(name='number_of_draws', value=100, section='MonteCarlo')
parameters.set_value(name='seed', value=1223, section='MonteCarlo')

# %%
# Create the Biogeme object.
the_biogeme = bio.BIOGEME(database, logprob, parameters=parameters)
the_biogeme.modelName = 'b25triangular_mixture'

# %%
# Estimate the parameters
results = the_biogeme.estimate()

# %%
print(results.short_summary())

# %%
pandas_results = results.get_estimated_parameters()
pandas_results
