mv 01logit.py b01logit.py
mv 01logitBis.py b01logitBis.py
mv 01logit_allAlgos.py b01logit_allAlgos.py
mv 01logit_simul.py b01logit_simul.py
mv 02weight.py b02weight.py
mv 03scale.py b03scale.py
mv 04validation.py b04validation.py
mv 05normalMixture.py b05normalMixture.py
mv 05normalMixtureIntegral.py b05normalMixtureIntegral.py
mv 05normalMixture_allAlgos.py b05normalMixture_allAlgos.py
mv 05normalMixture_simul.py b05normalMixture_simul.py
mv 06unifMixture.py b06unifMixture.py
mv 06unifMixtureIntegral.py b06unifMixtureIntegral.py
mv 06unifMixtureMHLS.py b06unifMixtureMHLS.py
mv 07discreteMixture.py b07discreteMixture.py
mv 08boxcox.py b08boxcox.py
mv 09nested.py b09nested.py
mv 09nested_allAlgos.py b09nested_allAlgos.py
mv 10nestedBottom.py b10nestedBottom.py
mv 11cnl.py b11cnl.py
mv 11cnl_simul.py b11cnl_simul.py
mv 11cnl_sparse.py b11cnl_sparse.py
mv 12panel.py b12panel.py
mv 12panel_flat.py b12panel_flat.py
mv 13panel_simul.py b13panel_simul.py
mv 14nestedEndogenousSampling.py b14nestedEndogenousSampling.py
mv 15panelDiscrete.py b15panelDiscrete.py
mv 15panelDiscreteBis.py b15panelDiscreteBis.py
mv 16panelDiscreteSocioEco.py b16panelDiscreteSocioEco.py
mv 17lognormalMixture.py b17lognormalMixture.py
mv 17lognormalMixtureIntegral.py b17lognormalMixtureIntegral.py
mv 18ordinalLogit.py b18ordinalLogit.py
mv 19individualLevelParameters.py b19individualLevelParameters.py
mv 20multipleModels.py b20multipleModels.py
mv 21probit.py b21probit.py
mv 24haltonMixture.py b24haltonMixture.py
mv 25triangularMixture.py b25triangularMixture.py
mv 26triangularPanelMixture.py b26triangularPanelMixture.py
