# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
import os
import re
import sys
import tomllib
from pathlib import Path

from biogeme.version import __version__

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

sys.path.insert(0, os.path.abspath('./extensions'))

project = 'Biogeme'
copyright = '2026, Michel Bierlaire'
author = 'Michel Bierlaire'

# The full version, including alpha/Beta/rc tags
release = __version__
language = 'en'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration


extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.doctest',
    'sphinx.ext.autosummary',
    'sphinx.ext.todo',
    'sphinx_autodoc_typehints',
    'sphinx_gallery.gen_gallery',
    'deprecated_extension',
]

# Section labels generated by ``autosectionlabel`` are otherwise global.  The
# example gallery contains many deliberately similar section headings (for
# example, ``Log-likelihood`` and ``Computation times``), so labels must be
# scoped to their document to avoid collisions between examples.
autosectionlabel_prefix_document = True

def gallery_pattern() -> str:
    """Return the execution pattern selected by the documentation profile."""
    profile = os.environ.get('BIOGEME_DOCS_GALLERY_PROFILE', 'full').lower()
    if profile == 'none':
        return r'(?!)'
    if profile == 'fast':
        manifest = Path(__file__).resolve().parents[2] / 'jed_runs' / 'jed_examples.toml'
        with manifest.open('rb') as manifest_file:
            configuration = tomllib.load(manifest_file)
        fast_examples = [
            name
            for name, metadata in configuration.get('docs', {}).get('examples', {}).items()
            if metadata.get('profile') == 'fast' and metadata.get('gallery', True)
        ]
        if not fast_examples:
            raise RuntimeError('The fast documentation profile has no examples.')
        alternatives = '|'.join(re.escape(name) for name in sorted(fast_examples))
        return rf'/(?:{alternatives})$'
    if profile != 'full':
        raise RuntimeError(f'Unknown BIOGEME_DOCS_GALLERY_PROFILE: {profile}')
    return r'/plot_'


sphinx_gallery_conf = {
    'examples_dirs': 'examples',  # Path to your example scripts
    'gallery_dirs': 'auto_examples',  # Path to save gallery generated output
    'filename_pattern': gallery_pattern(),
    # Only ``plot_*.py`` files are user-facing gallery examples.  The other
    # Python files in an example directory are data preparation, model
    # specification, or JED job-generation helpers.  Leaving them in the
    # gallery creates empty pages, thousands of ``toc.no_title`` warnings,
    # and can execute code that is not intended as a standalone example.
    # Sphinx-Gallery applies this regular expression to each basename (not
    # the full path), so the expression must not require a directory slash.
    'ignore_pattern': r'^(?!plot_[^/]+\.py$).*\.py$',
    'remove_config_comments': True,  # Remove config comments from examples
    'abort_on_example_error': True,
    'run_stale_examples': True,
}


# Explicitly disable localization
locale_dirs = []
gettext_compact = False

exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    'setup.py',
    'flycheck*',
    'verify_scripts.py',
    'generate_jed_run.py',
    # These repository-side notes are not part of the Sphinx navigation.
    # Keeping them as source files is useful for developers, but excluding
    # them avoids ``toc.not_included`` warnings during the documentation build.
    'examples/README.rst',
    'examples/**/README.rst',
    'working_examples/**/README.rst',
    # Legacy generated markers are not part of the public navigation.
    'sg_execution_times.rst',
    'code/README.rst',
]

# Set the behavior for type hints. Options are "none", "description", or "signature".
autodoc_typehints = 'description'
autodoc_typehints_format = 'short'
# Several public modules expose classes with the same short name (notably
# ``Beta``).  Qualified names make autodoc cross-references deterministic.
python_use_unqualified_type_names = False

autodoc_default_options = {
    'members': True,
    'undoc-members': True,
    'private-members': False,
    'show-inheritance': True,
}


def _skip_legacy_pickle_beta(app, what, name, obj, skip, options):
    """Keep the legacy pickle container out of the public API index.

    ``recycle_pickle.Beta`` is an internal compatibility container whose short
    name collides with the public expression ``Beta``.  It is not useful in the
    generated API reference and makes otherwise valid type references
    ambiguous.
    """
    if name == 'Beta' and getattr(obj, '__module__', '') == 'biogeme.results_processing.recycle_pickle':
        return True
    # ``automodule`` sees names imported into a module as members as well.
    # Their third-party docstrings (for example, JAX and NumPy's NumPy-style
    # documentation) are not part of Biogeme's API and can contain markup
    # that Docutils cannot parse in our reference pages.  Document the
    # Biogeme-owned object instead of duplicating another project's API here.
    object_module = getattr(obj, '__module__', '')
    if object_module and not object_module.startswith('biogeme'):
        return True
    return skip


def setup(app):
    app.connect('autodoc-skip-member', _skip_legacy_pickle_beta)

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'furo'
html_theme_options = {}
html_title = f'Biogeme {release} documentation'
html_static_path = ['_static']
