"""

26. Triangular mixture with panel data
======================================

 Bayesian estimation of a mixture of logit models.
 The mixing distribution is user-defined (triangular, here).
 The datafile is organized as panel data.

Michel Bierlaire, EPFL
Tue Nov 18 2025, 18:31:04

"""

from functools import partial

import biogeme.biogeme_logging as blog
import pymc as pm
from IPython.core.display_functions import display
from biogeme.bayesian_estimation import BayesianResults
from biogeme.biogeme import BIOGEME
from biogeme.expressions import (
    Beta,
    DistributedParameter,
    Draws,
)
from biogeme.models import loglogit
from biogeme.results_processing import (
    get_pandas_estimated_parameters,
)

# %%
# See the data processing script: :ref:`swissmetro_panel`.
from swissmetro_panel import (
    CAR_AV_SP,
    CAR_CO_SCALED,
    CAR_TT_SCALED,
    CHOICE,
    SM_AV,
    SM_COST_SCALED,
    SM_TT_SCALED,
    TRAIN_AV_SP,
    TRAIN_COST_SCALED,
    TRAIN_TT_SCALED,
    database,
)

logger = blog.get_screen_logger(level=blog.INFO)
logger.info('Example b26triangular_panel_mixture.py')

# %%
# The scale parameters must stay away from zero. We define a small but positive lower bound
POSITIVE_LOWER_BOUND = 1.0e-5

# %%
# Define a random parameter with a triangular distribution. The triangular distribution
# is not directly available from Biogeme. It has to be
# generated by a function provided by the user, based on PyMC available distributions.
#
# See the PyMC documentation:
# https://www.pymc.io/projects/docs/en/stable/api/distributions.html

# %%
# Mean of the distribution.
b_time = Beta('b_time', 0, None, None, 0)

# %%
# Scale of the distribution.
# It is advised not to use 0 as starting value for the following parameter.
b_time_s = Beta('b_time_s', 1, POSITIVE_LOWER_BOUND, None, 0)

# %%
# Distribution of the draws
TriangularFactory = partial(
    pm.Triangular,
    lower=-1.0,
    c=0.0,
    upper=1.0,
)

# %%
# Associate the function with a name
DISTRIBUTIONS = {'TRIANGULAR': TriangularFactory}


# %%
# Define a random parameter with a triangular distribution, designed to be used
# for Monte-Carlo simulation.
b_time_rnd = DistributedParameter(
    'b_time_rnd',
    b_time
    + b_time_s
    * Draws('b_time_rnd_err_term', 'TRIANGULAR', dict_of_distributions=DISTRIBUTIONS),
)

# %%
# Parameters to be estimated.
b_cost = Beta('b_cost', 0, None, None, 0)

# %%
# The constants are distributed across individuals, to address serial correlation.
# In a panel setting, the corresponding draws are generated at the individual level.
# Wrapping them in `DistributedParameter` ensures they are expanded consistently
# when combined with observation-level variables.
asc_car = Beta('asc_car', 0, None, None, 0)
asc_car_s = Beta('asc_car_s', 1, None, None, 0)
asc_car_rnd = DistributedParameter(
    'asc_car_rnd',
    asc_car
    + asc_car_s
    * Draws('asc_car_eps', 'TRIANGULAR', dict_of_distributions=DISTRIBUTIONS),
)

asc_train = Beta('asc_train', 0, None, None, 0)
asc_train_s = Beta('asc_train_s', 1, None, None, 0)
asc_train_rnd = DistributedParameter(
    'asc_train_rnd',
    asc_train
    + asc_train_s
    * Draws('asc_train_eps', 'TRIANGULAR', dict_of_distributions=DISTRIBUTIONS),
)

asc_sm = Beta('asc_sm', 0, None, None, 1)
asc_sm_s = Beta('asc_sm_s', 1, None, None, 0)
asc_sm_rnd = DistributedParameter(
    'asc_sm_rnd',
    asc_sm
    + asc_sm_s * Draws('asc_sm_eps', 'TRIANGULAR', dict_of_distributions=DISTRIBUTIONS),
)

# %%
# Definition of the utility functions.
v_train = asc_train_rnd + b_time_rnd * TRAIN_TT_SCALED + b_cost * TRAIN_COST_SCALED
v_swissmetro = asc_sm_rnd + b_time_rnd * SM_TT_SCALED + b_cost * SM_COST_SCALED
v_car = asc_car_rnd + b_time_rnd * CAR_TT_SCALED + b_cost * CAR_CO_SCALED

# %%
# Associate utility functions with the numbering of alternatives.
v = {1: v_train, 2: v_swissmetro, 3: v_car}

# %%
# Associate the availability conditions with the alternatives.
av = {1: TRAIN_AV_SP, 2: SM_AV, 3: CAR_AV_SP}

# %%
# Conditional to the random parameters, the likelihood of one observation is
# given by the logit model (called the kernel).
conditional_log_probability = loglogit(v, av, CHOICE)

# %%
# Create the Biogeme object.
the_biogeme = BIOGEME(
    database,
    conditional_log_probability,
)
the_biogeme.model_name = 'b26triangular_panel'

# %%
# Estimate the parameters.
try:
    results = BayesianResults.from_netcdf(
        filename=f'saved_results/{the_biogeme.model_name}.nc'
    )
except FileNotFoundError:
    results = the_biogeme.bayesian_estimation()

# %%
# Get the results in a pandas table
pandas_results = get_pandas_estimated_parameters(
    estimation_results=results,
)
display(pandas_results)
