#!/usr/bin/env python3
"""Plan and run documentation examples in isolated workspaces.

The command is intentionally small and dependency-free.  It reuses the JED
example discovery and dependency configuration, but never writes generated
files into ``docs/source/examples``.  Every local run gets a fresh workspace
under ``.docs_runs``.  The same metadata can therefore drive a quick local
check before the examples are migrated to the full Sphinx/JED workflow.

Examples::

    uv run python tools/docs_examples.py list
    uv run python tools/docs_examples.py plan --profile fast
    uv run python tools/docs_examples.py run --profile fast
    uv run python tools/docs_examples.py status

The runner is deliberately conservative: only examples explicitly marked
``profile = "fast"`` in the ``[docs.examples]`` section of
``jed_runs/jed_examples.toml`` are selected by the fast profile.  Exact
``expected_outputs`` and runtime-generated ``expected_output_globs`` are
validated in an isolated workspace before results are harvested.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_STATE_DIRECTORY = PROJECT_ROOT / '.docs_runs'

# These are generated by Biogeme or by the surrounding execution tools.  The
# runner excludes them when copying a source example into a clean workspace.
GENERATED_SUFFIXES = {
    '.F12',
    '.err',
    '.html',
    '.iter',
    '.log',
    '.nc',
    '.out',
    '.pareto',
    '.pickle',
    '.pkl',
    '.tex',
    '.yaml',
}
HARVEST_SUFFIXES = {'.html', '.nc', '.pareto', '.yaml'}
INPUT_CSV_NAMES = {'data.csv', 'optima.csv'}
INPUT_RESULT_DIRECTORIES = {'saved_results', 'saved_html'}


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec='seconds')


def json_dump(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + '.tmp')
    temporary.write_text(json.dumps(value, indent=2, sort_keys=True) + '\n')
    temporary.replace(path)


def json_load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def load_jed_module():
    """Import the existing discovery module when invoked from any directory."""
    if str(PROJECT_ROOT) not in sys.path:
        sys.path.insert(0, str(PROJECT_ROOT))
    from jed_runs import jed_examples

    return jed_examples


@dataclass(frozen=True)
class ExampleSpec:
    script: str
    source_directory: Path
    script_name: str
    mode: str
    profile: str
    dependencies: tuple[str, ...]
    required_inputs: tuple[str, ...]
    expected_outputs: tuple[str, ...]
    expected_output_globs: tuple[str, ...]
    requires_artifacts: bool
    gallery: bool


def load_config() -> dict[str, Any]:
    jed = load_jed_module()
    return jed.load_config()


def state_root(config: dict[str, Any]) -> Path:
    configured = os.environ.get(
        'BIOGEME_DOCS_STATE_DIRECTORY',
        config.get('docs', {}).get('state_directory', str(DEFAULT_STATE_DIRECTORY)),
    )
    path = Path(os.path.expandvars(os.path.expanduser(configured)))
    return path if path.is_absolute() else PROJECT_ROOT / path


def discover_specs(config: dict[str, Any]) -> dict[str, ExampleSpec]:
    """Build the documentation view of the shared JED example manifest."""
    jed = load_jed_module()
    jobs = jed.discover_jobs(config)
    docs_config = config.get('docs', {})
    overrides = docs_config.get('examples', {})
    specs: dict[str, ExampleSpec] = {}

    for script, job in jobs.items():
        override = overrides.get(script, {})
        mode = override.get(
            'mode', 'dependent' if job.dependencies else 'self_contained'
        )
        profile = override.get('profile', 'full')
        expected_outputs = tuple(override.get('expected_outputs', []))
        expected_output_globs = tuple(override.get('expected_output_globs', []))
        required_inputs = tuple(override.get('required_inputs', job.required_inputs))
        gallery = bool(override.get('gallery', True))
        specs[script] = ExampleSpec(
            script=script,
            source_directory=job.directory,
            script_name=job.script_name,
            mode=mode,
            profile=profile,
            dependencies=tuple(job.dependencies),
            required_inputs=required_inputs,
            expected_outputs=expected_outputs,
            expected_output_globs=expected_output_globs,
            requires_artifacts=bool(
                override.get('requires_artifacts', job.requires_artifacts)
            ),
            gallery=gallery,
        )

    for spec in specs.values():
        missing = [
            dependency for dependency in spec.dependencies if dependency not in specs
        ]
        if missing:
            raise ValueError(
                f'{spec.script} refers to missing dependency/dependencies: '
                + ', '.join(missing)
            )
    return specs


def select_specs(
    specs: dict[str, ExampleSpec], profile: str | None, requested: list[str]
) -> dict[str, ExampleSpec]:
    selected = set(requested)
    if requested:
        unknown = selected - specs.keys()
        if unknown:
            raise ValueError('Unknown example(s): ' + ', '.join(sorted(unknown)))
    else:
        selected = {
            name
            for name, spec in specs.items()
            if spec.gallery and (profile is None or spec.profile == profile)
        }

    # A selected post-processing example always brings its prerequisites along.
    changed = True
    while changed:
        changed = False
        for name in tuple(selected):
            for dependency in specs[name].dependencies:
                if dependency not in selected:
                    selected.add(dependency)
                    changed = True
    return {name: specs[name] for name in selected}


def topological_order(specs: dict[str, ExampleSpec]) -> list[ExampleSpec]:
    ordered: list[ExampleSpec] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(name: str) -> None:
        if name in visited:
            return
        if name in visiting:
            raise ValueError(f'Circular example dependency involving {name}')
        visiting.add(name)
        for dependency in specs[name].dependencies:
            if dependency in specs:
                visit(dependency)
        visiting.remove(name)
        visited.add(name)
        ordered.append(specs[name])

    for name in sorted(specs):
        visit(name)
    return ordered


def relative(path: Path) -> str:
    try:
        return path.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return str(path)


def should_copy(path: Path, source_directory: Path) -> bool:
    relative_parts = path.relative_to(source_directory).parts
    if any(part in {'.git', '__pycache__', '.pytest_cache'} for part in relative_parts):
        return False
    if any(part in INPUT_RESULT_DIRECTORIES for part in relative_parts):
        return False
    if path.name.startswith('slurm-') or path.name.endswith('_slurm.out'):
        return False
    if path.suffix == '.csv' and path.name in INPUT_CSV_NAMES:
        return True
    return path.suffix not in GENERATED_SUFFIXES and not path.name.endswith('.run')


def copy_source(source_directory: Path, destination: Path) -> None:
    """Copy authored source and inputs, excluding all known generated files."""
    destination.mkdir(parents=True, exist_ok=True)
    for source in sorted(source_directory.rglob('*')):
        if not should_copy(source, source_directory):
            continue
        target = destination / source.relative_to(source_directory)
        if source.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif source.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)


def copy_dependency_artifact(
    dependency_workspace: Path, consumer_workspace: Path, relative_path: str
) -> Path:
    source = dependency_workspace / relative_path
    if not source.is_file():
        # A predecessor may have created the result at the workspace root and
        # the harvester subsequently placed it in saved_results/saved_html.
        source = dependency_workspace / Path(relative_path).name
    if not source.is_file():
        raise FileNotFoundError(
            f'required artifact {relative_path} was not produced in '
            f'{dependency_workspace}'
        )
    destination = consumer_workspace / relative_path
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    return destination


def generated_files(workspace: Path) -> list[Path]:
    files: list[Path] = []
    for path in workspace.rglob('*'):
        if not path.is_file():
            continue
        relative_parts = path.relative_to(workspace).parts
        if any(
            part in {'.cache', '__pycache__', '.pytest_cache'}
            for part in relative_parts
        ):
            continue
        if any(part in INPUT_RESULT_DIRECTORIES for part in relative_parts):
            files.append(path)
            continue
        if path.suffix in GENERATED_SUFFIXES or (
            path.name.startswith('revenue_') and path.suffix == '.txt'
        ):
            files.append(path)
    return sorted(files)


def harvest(workspace: Path) -> list[str]:
    """Archive outputs written at the workspace root or archive paths."""
    harvested: list[str] = []
    roots = [workspace]
    roots.extend(
        workspace / result_directory
        for result_directory in sorted(INPUT_RESULT_DIRECTORIES)
        if (workspace / result_directory).is_dir()
    )
    sources = [
        source
        for root in roots
        for source in sorted(root.iterdir())
        if source.is_file() and source.suffix in HARVEST_SUFFIXES
    ]
    for source in sources:
        directory_name = 'saved_html' if source.suffix == '.html' else 'saved_results'
        target = workspace / directory_name / source.name
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.resolve() != target.resolve():
            shutil.copy2(source, target)
        harvested.append(target.relative_to(workspace).as_posix())
    return harvested


def expected_output_paths(workspace: Path, expected: str) -> tuple[Path, ...]:
    """Return root and archive locations for one logical output name."""
    relative = Path(expected)
    if relative.parts and relative.parts[0] in INPUT_RESULT_DIRECTORIES:
        return (workspace / relative,)
    candidates = [workspace / relative]
    if relative.suffix.lower() == '.html':
        candidates.append(workspace / 'saved_html' / relative.name)
    elif relative.suffix.lower() in HARVEST_SUFFIXES:
        candidates.append(workspace / 'saved_results' / relative.name)
    return tuple(candidates)


def expected_output_glob_matches(workspace: Path, pattern: str) -> list[Path]:
    """Match a declared output pattern at the root and archive locations."""
    relative = Path(pattern)
    if relative.parts and relative.parts[0] in INPUT_RESULT_DIRECTORIES:
        roots = (workspace,)
    elif relative.suffix.lower() == '.html':
        roots = (workspace, workspace / 'saved_html')
    elif relative.suffix.lower() in HARVEST_SUFFIXES:
        roots = (workspace, workspace / 'saved_results')
    else:
        roots = (workspace,)
    return [
        path
        for root in roots
        if root.is_dir()
        for path in root.glob(pattern)
        if path.is_file()
    ]


def validate_outputs(
    spec: ExampleSpec, workspace: Path, harvested: list[str]
) -> list[str]:
    errors: list[str] = []
    for expected in spec.expected_outputs:
        if not any(
            path.is_file() for path in expected_output_paths(workspace, expected)
        ):
            errors.append(f'missing expected output: {expected}')
    for pattern in spec.expected_output_globs:
        if not expected_output_glob_matches(workspace, pattern):
            errors.append(f'missing expected output matching pattern: {pattern}')
    if spec.requires_artifacts and not generated_files(workspace):
        errors.append('no generated result/report artifact was produced')
    harvestable_expected = any(
        Path(expected).suffix in HARVEST_SUFFIXES for expected in spec.expected_outputs
    )
    harvestable_expected = harvestable_expected or any(
        Path(pattern).suffix in HARVEST_SUFFIXES
        for pattern in spec.expected_output_globs
    )
    if harvestable_expected and not harvested:
        # Expected outputs are allowed to be non-harvestable files, but this
        # diagnostic catches a common mistake in estimation examples.
        errors.append('expected outputs were not archived in the workspace')
    return errors


def run_one(
    spec: ExampleSpec,
    run_directory: Path,
    workspace_by_script: dict[str, Path],
    python_executable: str,
) -> dict[str, Any]:
    slug = spec.script.removesuffix('.py').replace('/', '__')
    job_directory = run_directory / 'jobs' / slug
    workspace = run_directory / 'workspaces' / slug
    job_directory.mkdir(parents=True, exist_ok=True)
    copy_source(spec.source_directory, workspace)

    try:
        for dependency in spec.dependencies:
            dependency_workspace = workspace_by_script[dependency]
            for required_input in spec.required_inputs:
                copy_dependency_artifact(
                    dependency_workspace, workspace, required_input
                )
    except (FileNotFoundError, KeyError) as error:
        diagnostic = str(error)
        (job_directory / 'stderr.txt').write_text(diagnostic + '\n')
        return {
            'script': spec.script,
            'status': 'blocked',
            'exit_code': None,
            'diagnostics': [diagnostic],
            'workspace': str(workspace),
        }

    environment = os.environ.copy()
    cache = workspace / '.cache'
    environment.update(
        {
            'PYTHONUNBUFFERED': '1',
            'PYTHONHASHSEED': '0',
            'MPLBACKEND': 'Agg',
            'MPLCONFIGDIR': str(cache / 'matplotlib'),
            'XDG_CACHE_HOME': str(cache),
            'BIOGEME_DOCS_EXAMPLE': spec.script,
            'BIOGEME_DOCS_EXAMPLE_OUTPUT_DIR': str(workspace / 'outputs'),
            'OMP_NUM_THREADS': '1',
            'OPENBLAS_NUM_THREADS': '1',
            'MKL_NUM_THREADS': '1',
            'NUMEXPR_NUM_THREADS': '1',
        }
    )
    (workspace / 'outputs').mkdir(parents=True, exist_ok=True)
    started = time.monotonic()
    process = subprocess.run(
        [python_executable, '-u', spec.script_name],
        cwd=workspace,
        env=environment,
        text=True,
        capture_output=True,
        check=False,
    )
    duration = time.monotonic() - started
    (job_directory / 'stdout.txt').write_text(process.stdout)
    (job_directory / 'stderr.txt').write_text(process.stderr)
    harvested = harvest(workspace) if process.returncode == 0 else []
    diagnostics = validate_outputs(spec, workspace, harvested)
    status = 'success' if process.returncode == 0 and not diagnostics else 'failed'
    if process.returncode:
        diagnostics.insert(0, f'example exited with code {process.returncode}')
    result = {
        'script': spec.script,
        'status': status,
        'exit_code': process.returncode,
        'duration_seconds': round(duration, 3),
        'dependencies': list(spec.dependencies),
        'required_inputs': list(spec.required_inputs),
        'expected_outputs': list(spec.expected_outputs),
        'expected_output_globs': list(spec.expected_output_globs),
        'harvested_outputs': harvested,
        'diagnostics': diagnostics,
        'workspace': str(workspace),
    }
    json_dump(job_directory / 'result.json', result)
    # Keep the workspace until the complete dependency graph has finished:
    # downstream examples consume the predecessor's harvested artifacts.
    # ``command_run`` removes successful workspaces after the graph completes.
    return result


def command_list(args: argparse.Namespace) -> int:
    specs = discover_specs(load_config())
    for spec in sorted(specs.values(), key=lambda item: item.script):
        print(
            f'{spec.script:65} {spec.profile:10} {spec.mode:14} '
            f'depends={len(spec.dependencies)} gallery={spec.gallery}'
        )
    print(f'\nTotal examples: {len(specs)}')
    return 0


def command_plan(args: argparse.Namespace) -> int:
    specs = discover_specs(load_config())
    selected = select_specs(specs, args.profile, args.script or [])
    ordered = topological_order(selected)
    for index, spec in enumerate(ordered, start=1):
        dependencies = ', '.join(spec.dependencies) or '-'
        print(f'{index:3}. {spec.script}  [{spec.profile}]  <- {dependencies}')
    print(f'\nPlanned examples: {len(ordered)}')
    return 0


def command_run(args: argparse.Namespace) -> int:
    config = load_config()
    specs = discover_specs(config)
    selected = select_specs(specs, args.profile, args.script or [])
    ordered = topological_order(selected)
    root = state_root(config)
    run_id = args.run_id or datetime.now().strftime('%Y%m%d-%H%M%S')
    run_directory = root / run_id
    if run_directory.exists() and not args.force:
        raise ValueError(f'Run directory already exists: {run_directory}')
    run_directory.mkdir(parents=True, exist_ok=True)
    python_executable = args.python or sys.executable
    run_record: dict[str, Any] = {
        'run_id': run_id,
        'created_at': now_iso(),
        'python': python_executable,
        'profile': args.profile,
        'jobs': {},
    }
    workspace_by_script: dict[str, Path] = {}
    failures = 0
    for spec in ordered:
        workspace_by_script[spec.script] = (
            run_directory
            / 'workspaces'
            / spec.script.removesuffix('.py').replace('/', '__')
        )
        dependency_failures = [
            dependency
            for dependency in spec.dependencies
            if run_record['jobs'].get(dependency, {}).get('status')
            not in {'success', 'planned'}
        ]
        if dependency_failures:
            result = {
                'script': spec.script,
                'status': 'blocked',
                'exit_code': None,
                'diagnostics': ['dependency failed: ' + ', '.join(dependency_failures)],
            }
        elif args.dry_run:
            result = {
                'script': spec.script,
                'status': 'planned',
                'exit_code': None,
                'dependencies': list(spec.dependencies),
            }
        else:
            result = run_one(
                spec,
                run_directory,
                workspace_by_script,
                python_executable,
            )
        run_record['jobs'][spec.script] = result
        json_dump(run_directory / 'run.json', run_record)
        print(f'{result["status"]:8} {spec.script}')
        if result['status'] not in {'success', 'planned'}:
            failures += 1
            if not args.continue_on_error:
                break
    if not args.keep_workspace and not args.dry_run:
        for spec in ordered:
            result = run_record['jobs'].get(spec.script, {})
            workspace = workspace_by_script.get(spec.script)
            if workspace and result.get('status') == 'success' and workspace.exists():
                shutil.rmtree(workspace)
    print(f'Run state: {run_directory}')
    return 1 if failures else 0


def command_status(args: argparse.Namespace) -> int:
    config = load_config()
    root = state_root(config)
    run_directory = root / args.run_id if args.run_id else latest_run(root)
    if run_directory is None or not (run_directory / 'run.json').is_file():
        raise ValueError('No documentation example run was found.')
    record = json_load(run_directory / 'run.json')
    counts: dict[str, int] = {}
    print(f'Run {record["run_id"]} ({record.get("created_at", "unknown")})')
    for script, result in record.get('jobs', {}).items():
        status = result.get('status', 'unknown')
        counts[status] = counts.get(status, 0) + 1
        print(f'{status:10} {script}')
        if args.verbose:
            for diagnostic in result.get('diagnostics', []):
                print(f'  {diagnostic}')
    print(
        'Summary: '
        + ', '.join(f'{key}={value}' for key, value in sorted(counts.items()))
    )
    return 0 if not any(key in counts for key in ('failed', 'blocked')) else 1


def latest_run(root: Path) -> Path | None:
    if not root.is_dir():
        return None
    candidates = [path for path in root.iterdir() if path.is_dir()]
    return (
        max(candidates, key=lambda path: path.stat().st_mtime) if candidates else None
    )


def command_clean(args: argparse.Namespace) -> int:
    root = state_root(load_config())
    if not root.exists():
        print(f'Nothing to clean: {relative(root)}')
        return 0
    if not args.apply:
        print(f'Dry run: would remove {relative(root)}')
        return 0
    resolved_root = root.resolve()
    if resolved_root in {PROJECT_ROOT.resolve(), Path('/')}:
        raise ValueError(f'Refusing to remove unsafe documentation state path: {root}')
    shutil.rmtree(root)
    print(f'Removed {relative(root)}')
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest='command', required=True)

    list_command = subparsers.add_parser('list', help='list discovered examples')
    list_command.set_defaults(function=command_list)

    plan = subparsers.add_parser('plan', help='show the selected dependency plan')
    plan.add_argument('--profile', choices=['fast', 'full'])
    plan.add_argument('--script', action='append', help='select one or more scripts')
    plan.set_defaults(function=command_plan)

    run = subparsers.add_parser('run', help='run examples in fresh workspaces')
    run.add_argument('--profile', choices=['fast', 'full'])
    run.add_argument('--script', action='append', help='select one or more scripts')
    run.add_argument('--python', help='Python executable; defaults to this interpreter')
    run.add_argument('--run-id')
    run.add_argument('--force', action='store_true')
    run.add_argument('--dry-run', action='store_true')
    run.add_argument('--continue-on-error', action='store_true')
    run.add_argument('--keep-workspace', action='store_true')
    run.set_defaults(function=command_run)

    status = subparsers.add_parser('status', help='summarize a documentation run')
    status.add_argument('--run-id')
    status.add_argument('--verbose', action='store_true')
    status.set_defaults(function=command_status)

    clean = subparsers.add_parser('clean', help='remove local documentation run state')
    clean.add_argument('--apply', action='store_true')
    clean.set_defaults(function=command_clean)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.function(args)
    except (OSError, ValueError, RuntimeError, ImportError) as error:
        print(f'error: {error}', file=sys.stderr)
        return 2


if __name__ == '__main__':
    raise SystemExit(main())
