"""Generate the generated API and configuration documentation tree.

The files under ``docs/source/code`` are generated artifacts.  This script
builds them in a temporary directory and replaces the destination only after
the complete tree has been validated.  That makes a failed documentation
build recoverable: the previously generated tree remains available.
"""

from __future__ import annotations

import argparse
import os
import shutil
import tempfile
import uuid
from dataclasses import dataclass
from pathlib import Path

DEFAULT_EXCLUDED_DIRS = frozenset(
    {
        'biogeme.egg-info',
        '__pycache__',
        'latent_variables_old',
        'working_examples',
    }
)
DEFAULT_EXCLUDED_FILES = frozenset(
    {
        '__init__.py',
        'generate_jed_run.py',
        'logging_tmp.py',
    }
)
GENERATED_METADATA = frozenset(
    {
        Path('README.rst'),
        Path('biogeme.toml'),
        Path('biogeme_api.rst'),
        Path('native_draws.rst'),
        Path('toml.rst'),
    }
)


@dataclass(frozen=True)
class ModulePage:
    """A Python module and its generated RST path."""

    module: str
    source: Path
    relative_rst: Path


def _write_text(filename: Path, content: str) -> None:
    """Write generated text with stable encoding and line endings."""

    filename.parent.mkdir(parents=True, exist_ok=True)
    with filename.open('w', encoding='utf-8', newline='\n') as stream:
        stream.write(content)


def _normalise_cell(value: object) -> str:
    """Make a value safe for a one-line list-table cell."""

    return ' '.join(str(value).split())


def _type_name(value: object) -> str:
    """Return a stable, human-readable name for a parameter type."""

    name = getattr(value, '__name__', None)
    if isinstance(name, str):
        return name

    text = str(value)
    if text.startswith('builtins.'):
        return text.removeprefix('builtins.')
    return text


def readme_file(filename: str | Path) -> None:
    """Write the marker file for the generated documentation directory."""

    title = 'Generated documentation for Biogeme'
    content = (
        f'{title}\n'
        f'{"=" * len(title)}\n\n'
        'This directory is generated by ``docs/create_code_rst.py``.\n'
        'Its content should not be manually edited.\n'
    )
    _write_text(Path(filename), content)


def draws_documentation(filename: str | Path) -> None:
    """Generate the native-draw reference page."""

    # Import these at generation time so module discovery and validation do
    # not import the full Biogeme runtime unnecessarily.
    from biogeme.draws import description_of_native_draws

    description: dict[str, str] = description_of_native_draws()
    title = 'Native draws'
    lines = [
        title,
        '=' * len(title),
        '',
        'The generation of draws is performed using the command '
        '``Draws("var", "DRAW_TYPE")``, where ``var`` is the name of the '
        'random variable and ``DRAW_TYPE`` is its distribution.',
        '',
        'See the :class:`~biogeme.expressions.elementary_expressions.Draws` '
        'documentation for the complete API. Draw types can be user-defined '
        'or selected from the native draws listed below.',
        '',
        'See `Bierlaire (2019) '
        '<https://transp-or.epfl.ch/documents/technicalReports/Bier19.pdf>`_ '
        'for details on the native draw generators.',
        '',
        '.. list-table::',
        '   :header-rows: 1',
        '',
        '   * - Name',
        '     - Description',
    ]
    for name, desc in sorted(description.items()):
        lines.extend(
            [
                f'   * - ``{_normalise_cell(name)}``',
                f'     - {_normalise_cell(desc)}',
            ]
        )

    _write_text(Path(filename), '\n'.join(lines) + '\n')


def toml_documentation(filename: str | Path) -> None:
    """Generate the configuration-parameter reference page."""

    from biogeme.default_parameters import all_parameters_tuple

    all_parameters = all_parameters_tuple()
    grouped_by_section: dict[str, list[object]] = {}
    for parameter in all_parameters:
        grouped_by_section.setdefault(parameter.section, []).append(parameter)
    for parameters in grouped_by_section.values():
        parameters.sort(key=lambda parameter: parameter.name)

    title = 'Configuration parameters'
    lines = [
        title,
        '=' * len(title),
        '',
        'Biogeme can be configured using a parameter file. By default, the '
        'file is named ``biogeme.toml``. If it does not exist, Biogeme creates '
        'one containing the default values.',
        '',
        '.. list-table::',
        '   :header-rows: 1',
        '',
        '   * - Name',
        '     - Description',
        '     - Default',
        '     - Section',
        '     - Type',
    ]
    for section in sorted(grouped_by_section):
        for parameter in grouped_by_section[section]:
            lines.extend(
                [
                    f'   * - {_normalise_cell(parameter.name)}',
                    f'     - {_normalise_cell(parameter.description)}',
                    f'     - {_normalise_cell(parameter.value)}',
                    f'     - {_normalise_cell(section)}',
                    f'     - {_normalise_cell(_type_name(parameter.type))}',
                ]
            )

    lines.extend(
        [
            '',
            'The structure of the ``biogeme.toml`` file is as follows.',
            '',
            '.. literalinclude:: biogeme.toml',
            '   :language: none',
            '   :linenos:',
            '',
        ]
    )
    _write_text(Path(filename), '\n'.join(lines) + '\n')


def _excluded_directory(name: str, excluded_dirs: frozenset[str]) -> bool:
    """Return whether a source directory should not be documented."""

    return name.startswith('.') or name in excluded_dirs


def discover_modules(
    src_dir: str | Path,
    *,
    excluded_dirs: frozenset[str] = DEFAULT_EXCLUDED_DIRS,
    excluded_files: frozenset[str] = DEFAULT_EXCLUDED_FILES,
) -> tuple[ModulePage, ...]:
    """Discover Python modules and their deterministic generated paths."""

    source_root = Path(src_dir).resolve()
    if not source_root.is_dir():
        raise FileNotFoundError(f'Source directory does not exist: {source_root}')

    pages: list[ModulePage] = []
    seen_modules: dict[str, Path] = {}
    for root, directories, filenames in os.walk(source_root):
        directories[:] = sorted(
            name for name in directories if not _excluded_directory(name, excluded_dirs)
        )
        root_path = Path(root)
        for filename in sorted(filenames):
            if (
                not filename.endswith('.py')
                or filename in excluded_files
                or filename.startswith('.')
            ):
                continue

            source_file = root_path / filename
            relative = source_file.relative_to(source_root)
            relative_rst = relative.with_suffix('.rst')
            module = '.'.join(relative_rst.with_suffix('').parts)
            invalid_parts = [
                part for part in module.split('.') if not part.isidentifier()
            ]
            if invalid_parts:
                raise ValueError(
                    f'Cannot generate a Python module path for {source_file}: '
                    f'invalid component(s) {invalid_parts}'
                )
            if module in seen_modules:
                raise ValueError(
                    f'Multiple source files generate module {module}: '
                    f'{seen_modules[module]} and {source_file}'
                )
            seen_modules[module] = source_file
            pages.append(
                ModulePage(
                    module=module,
                    source=source_file,
                    relative_rst=relative_rst,
                )
            )

    return tuple(sorted(pages, key=lambda page: page.relative_rst.as_posix()))


def _directory_indexes(pages: tuple[ModulePage, ...]) -> tuple[Path, ...]:
    """Return package directories that need a generated index page."""

    directories: set[Path] = set()
    for page in pages:
        parent = page.relative_rst.parent
        while parent != Path('.'):
            directories.add(parent)
            parent = parent.parent
    return tuple(sorted(directories, key=lambda path: path.as_posix()))


def _index_path(directory: Path) -> Path:
    """Return the RST path for a package directory index."""

    return directory / 'index.rst'


def _api_index_path() -> Path:
    """Return the generated top-level API entry-point path."""

    return Path('biogeme_api.rst')


def _write_module_page(destination: Path, page: ModulePage) -> None:
    """Write one autodoc page for a Python module."""

    title = f'{page.module} module'
    content = (
        f'{title}\n'
        f'{"+" * len(title)}\n\n'
        f'.. automodule:: {page.module}\n'
        '   :members:\n'
        '   :show-inheritance:\n'
    )
    _write_text(destination, content)


def _write_directory_index(
    destination: Path, module_name: str, entries: list[Path]
) -> None:
    """Write a toctree page for one package directory."""

    if not entries:
        raise ValueError(f'Cannot write an empty directory index: {destination}')
    title = f'{module_name} module'
    lines = [
        title,
        '=' * len(title),
        '',
        '.. toctree::',
        '   :maxdepth: 2',
        '',
    ]
    lines.extend(f'   {entry.as_posix()}' for entry in entries)
    _write_text(destination, '\n'.join(lines) + '\n')


def _write_api_index(destination: Path, pages: tuple[ModulePage, ...]) -> None:
    """Write the stable top-level entry point for the generated API tree."""

    root_packages = sorted({page.relative_rst.parts[0] for page in pages})
    if not root_packages:
        raise ValueError('Cannot generate an API index without Python modules')

    title = 'Biogeme API reference'
    lines = [
        title,
        '=' * len(title),
        '',
        'This reference is generated from the Python modules under ``src``. '
        'For a conceptual introduction, see :doc:`../biogeme_overview`.',
        '',
        '.. toctree::',
        '   :maxdepth: 2',
        '',
    ]
    lines.extend(
        f'   {_index_path(Path(package)).as_posix()}' for package in root_packages
    )
    _write_text(destination, '\n'.join(lines) + '\n')


def _expected_paths(pages: tuple[ModulePage, ...]) -> set[Path]:
    """Return every path that the generator is expected to create."""

    expected = set(GENERATED_METADATA)
    expected.update(page.relative_rst for page in pages)
    expected.update(_index_path(directory) for directory in _directory_indexes(pages))
    return expected


def validate_generated_tree(
    destination: str | Path, pages: tuple[ModulePage, ...]
) -> None:
    """Validate the generated tree and reject stale or unexpected files."""

    root = Path(destination)
    if not root.is_dir():
        raise FileNotFoundError(f'Generated directory does not exist: {root}')

    actual = {path.relative_to(root) for path in root.rglob('*') if path.is_file()}
    expected = _expected_paths(pages)
    unexpected = sorted(actual - expected, key=lambda path: path.as_posix())
    missing = sorted(expected - actual, key=lambda path: path.as_posix())
    if unexpected or missing:
        details = []
        if unexpected:
            details.append(
                'unexpected: ' + ', '.join(path.as_posix() for path in unexpected)
            )
        if missing:
            details.append('missing: ' + ', '.join(path.as_posix() for path in missing))
        raise RuntimeError(
            'Generated documentation tree is invalid (' + '; '.join(details) + ')'
        )

    for page in pages:
        generated = root / page.relative_rst
        text = generated.read_text(encoding='utf-8')
        marker = f'.. automodule:: {page.module}'
        if marker not in text:
            raise RuntimeError(f'Module directive missing from {generated}')


def _generate_tree(destination: Path, pages: tuple[ModulePage, ...]) -> None:
    """Populate a staging directory with all generated files."""

    readme_file(destination / 'README.rst')
    draws_documentation(destination / 'native_draws.rst')
    toml_documentation(destination / 'toml.rst')

    from biogeme.parameters import Parameters

    Parameters().dump_file(file_name=str(destination / 'biogeme.toml'))

    module_paths = {page.relative_rst for page in pages}
    generated_paths = set(GENERATED_METADATA)
    index_paths = {_index_path(directory) for directory in _directory_indexes(pages)}
    collision = module_paths & (generated_paths | index_paths)
    if collision:
        paths = ', '.join(sorted(path.as_posix() for path in collision))
        raise RuntimeError(f'Generated documentation paths collide: {paths}')

    _write_api_index(destination / _api_index_path(), pages)
    for page in pages:
        _write_module_page(destination / page.relative_rst, page)

    for directory in _directory_indexes(pages):
        index_path = _index_path(directory)
        entries: list[Path] = []
        for page in pages:
            if page.relative_rst.parent == directory:
                entries.append(page.relative_rst.relative_to(index_path.parent))
        for child in _directory_indexes(pages):
            if child.parent == directory:
                entries.append(_index_path(child).relative_to(index_path.parent))
        entries.sort(key=lambda path: path.as_posix())
        module_name = '.'.join(directory.parts)
        _write_directory_index(destination / index_path, module_name, entries)


def _replace_directory(staging: Path, destination: Path) -> None:
    """Replace ``destination`` with ``staging`` and roll back on failure."""

    backup: Path | None = None
    if destination.exists():
        if not destination.is_dir():
            raise NotADirectoryError(f'Destination is not a directory: {destination}')
        backup = destination.with_name(f'.{destination.name}.backup-{uuid.uuid4().hex}')
        destination.rename(backup)
    try:
        staging.rename(destination)
    except Exception:
        if backup is not None and not destination.exists():
            backup.rename(destination)
        raise
    if backup is not None:
        shutil.rmtree(backup)


def create_rst_structure(
    src_dir: str | Path,
    dst_dir: str | Path,
    force: bool = False,
) -> None:
    """Generate and validate the API tree, replacing it only on success."""

    source = Path(src_dir).resolve()
    destination = Path(dst_dir).resolve()
    pages = discover_modules(source)
    if destination.exists() and not force:
        raise RuntimeError(
            f'The destination directory {destination} already exists. '
            'Use --force to replace generated documentation.'
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(
        tempfile.mkdtemp(prefix=f'.{destination.name}.', dir=str(destination.parent))
    )
    try:
        _generate_tree(staging, pages)
        validate_generated_tree(staging, pages)
        _replace_directory(staging, destination)
        print(f'Generated and validated {len(pages)} module pages in {destination}')
    except Exception:
        if staging.exists():
            shutil.rmtree(staging)
        raise


def check_rst_structure(src_dir: str | Path, dst_dir: str | Path) -> None:
    """Validate an existing generated tree without modifying it."""

    pages = discover_modules(src_dir)
    validate_generated_tree(dst_dir, pages)
    print(f'Validated {len(pages)} module pages in {Path(dst_dir).resolve()}')


def _argument_parser() -> argparse.ArgumentParser:
    docs_directory = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description='Generate the ignored API/configuration RST tree.'
    )
    parser.add_argument(
        '--force',
        action='store_true',
        help='replace the existing generated tree after successful validation',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='validate the existing generated tree without modifying it',
    )
    parser.add_argument(
        '--src',
        type=Path,
        default=docs_directory.parent / 'src',
        help='source tree to document (default: repository src directory)',
    )
    parser.add_argument(
        '--dst',
        type=Path,
        default=docs_directory / 'source' / 'code',
        help='generated RST destination (default: docs/source/code)',
    )
    return parser


if __name__ == '__main__':
    arguments = _argument_parser().parse_args()
    if arguments.check:
        check_rst_structure(arguments.src, arguments.dst)
    else:
        create_rst_structure(arguments.src, arguments.dst, force=arguments.force)
