name: Build & publish (pure Python)

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build sdist + universal wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean dist
        run: rm -rf dist && mkdir -p dist   # 👈 this ensures it's empty

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'   # any supported version is fine for pure-python

      - name: Install build tooling
        run: python -m pip install --upgrade pip build

      - name: Build distributions
        run: python -m build --sdist --wheel --outdir dist/

      - name: Show artifacts
        run: ls -l dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  pypi-publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write    # required for Trusted Publishing (OIDC)
      contents: read
    steps:
      - name: Download built dists
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1